# Manthan: Google Earth Engine Environment Configuration
# Optimized for geospatial AI and forest restoration analysis

name: manthan-gee
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # Google Earth Engine & Geospatial Core
  - earthengine-api>=1.6.0
  - geemap>=0.33.0
  - geopandas>=1.1.0
  - rasterio>=1.4.0
  - shapely>=2.0.0
  - fiona>=1.9.0
  - pyproj>=3.6.0
  - folium>=0.20.0
  - contextily>=1.4.0
  
  # Dashboard & Visualization
  - streamlit>=1.35.0
  - streamlit-folium>=0.20.0
  - plotly>=5.17.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - ipywidgets>=8.1.0
  
  # Machine Learning & AI
  - scikit-learn>=1.4.0
  - numpy>=1.26.0
  - pandas>=2.1.0
  - xarray>=2024.1.0
  - scipy>=1.12.0
  
  # Data Processing
  - requests>=2.31.0
  - netcdf4>=1.6.0
  - h5py>=3.10.0
  - openpyxl>=3.1.0
  
  # Development Tools
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.1.0
  
  # Additional GEE Dependencies via pip
  - pip
  - pip:
    - earthengine-api>=1.6.0
    - geemap>=0.33.0
    - pygbif>=0.6.0  # GBIF API for species data
    - pystac-client>=0.8.0  # STAC catalog access
    - python-dotenv>=1.0.0  # Environment variables
    - streamlit-authenticator>=0.3.0  # User authentication
    - reportlab>=4.0.0  # PDF generation
    - leafmap>=0.36.0  # Alternative mapping libraryy