"""
Comprehensive Indian Forest Ecological Data
Based on Champion & Seth classification, GBIF data, and regional studies
"""

from .indian_forest_knowledge_graph import SpeciesTraits, ForestTypeData
from typing import Dict, List

class IndianForestData:
    """
    Comprehensive database of Indian forest types and species
    Based on scientific literature and field studies
    """
    
    @staticmethod
    def get_forest_types() -> Dict[str, ForestTypeData]:
        """Get all Indian forest types with complete data"""
        return {
            # Western Ghats Wet Evergreen
            "Tropical Wet Evergreen": ForestTypeData(
                name="Tropical Wet Evergreen",
                champion_seth_code="1A/C1",
                description="Dense, multi-layered evergreen forests of Western Ghats with high endemism",
                typical_states=["Kerala", "Karnataka", "Tamil Nadu", "Maharashtra", "Goa"],
                rainfall_range=(2500, 7000),
                temperature_range=(18, 32),
                elevation_range=(0, 1500),
                soil_ph_range=(4.5, 6.5),
                soil_types=["Laterite", "Red loam", "Forest loam"],
                canopy_cover_percent=(80, 95),
                layer_proportions={
                    "emergent": 0.15,
                    "canopy": 0.50,
                    "understory": 0.30,
                    "shrub": 0.04,
                    "ground": 0.01
                },
                succession_stage="climax",
                disturbance_regime=["cyclone", "landslide"],
                conservation_priority=5,
                restoration_difficulty=4,
                typical_species_richness=150,
                carbon_storage_potential=350,
                water_regulation_capacity=5,
                soil_conservation_value=5
            ),
            
            # Central Indian Dry Deciduous
            "Tropical Dry Deciduous": ForestTypeData(
                name="Tropical Dry Deciduous",
                champion_seth_code="5A/C1",
                description="Deciduous forests of Central India dominated by Sal and Teak",
                typical_states=["Madhya Pradesh", "Chhattisgarh", "Jharkhand", "Maharashtra", "Odisha"],
                rainfall_range=(800, 1600),
                temperature_range=(15, 45),
                elevation_range=(200, 1000),
                soil_ph_range=(6.0, 7.5),
                soil_types=["Red soil", "Alluvial", "Black cotton soil"],
                canopy_cover_percent=(40, 70),
                layer_proportions={
                    "emergent": 0.10,
                    "canopy": 0.55,
                    "understory": 0.30,
                    "shrub": 0.04,
                    "ground": 0.01
                },
                succession_stage="mature",
                disturbance_regime=["fire", "drought", "grazing"],
                conservation_priority=3,
                restoration_difficulty=2,
                typical_species_richness=80,
                carbon_storage_potential=200,
                water_regulation_capacity=3,
                soil_conservation_value=4
            ),
            
            # Himalayan Subtropical
            "Himalayan Subtropical Pine": ForestTypeData(
                name="Himalayan Subtropical Pine",
                champion_seth_code="9/C2",
                description="Pine-dominated forests of lower Himalayas",
                typical_states=["Himachal Pradesh", "Uttarakhand", "Jammu and Kashmir"],
                rainfall_range=(1000, 2500),
                temperature_range=(5, 30),
                elevation_range=(1000, 2000),
                soil_ph_range=(5.5, 7.0),
                soil_types=["Mountain soil", "Brown forest soil"],
                canopy_cover_percent=(60, 80),
                layer_proportions={
                    "emergent": 0.05,
                    "canopy": 0.70,
                    "understory": 0.20,
                    "shrub": 0.04,
                    "ground": 0.01
                },
                succession_stage="mature",
                disturbance_regime=["fire", "landslide", "snow"],
                conservation_priority=4,
                restoration_difficulty=3,
                typical_species_richness=60,
                carbon_storage_potential=180,
                water_regulation_capacity=4,
                soil_conservation_value=5
            ),
            
            # Rajasthan Arid
            "Tropical Thorn Forest": ForestTypeData(
                name="Tropical Thorn Forest",
                champion_seth_code="6A/DS1",
                description="Arid zone forests of Rajasthan and Gujarat",
                typical_states=["Rajasthan", "Gujarat", "Haryana"],
                rainfall_range=(200, 600),
                temperature_range=(5, 50),
                elevation_range=(100, 500),
                soil_ph_range=(7.0, 8.5),
                soil_types=["Desert soil", "Sandy soil", "Saline soil"],
                canopy_cover_percent=(10, 40),
                layer_proportions={
                    "emergent": 0.02,
                    "canopy": 0.35,
                    "understory": 0.50,
                    "shrub": 0.12,
                    "ground": 0.01
                },
                succession_stage="pioneer",
                disturbance_regime=["drought", "grazing", "sand storms"],
                conservation_priority=4,
                restoration_difficulty=5,
                typical_species_richness=30,
                carbon_storage_potential=50,
                water_regulation_capacity=2,
                soil_conservation_value=3
            ),
            
            # Eastern Himalayan Subtropical
            "Eastern Himalayan Subtropical Broadleaf": ForestTypeData(
                name="Eastern Himalayan Subtropical Broadleaf",
                champion_seth_code="8A/C2",
                description="Broadleaf forests of Eastern Himalayas with high diversity",
                typical_states=["Sikkim", "Arunachal Pradesh", "West Bengal", "Assam"],
                rainfall_range=(1500, 4000),
                temperature_range=(10, 28),
                elevation_range=(500, 2000),
                soil_ph_range=(5.0, 6.5),
                soil_types=["Mountain soil", "Forest soil", "Alluvial"],
                canopy_cover_percent=(70, 90),
                layer_proportions={
                    "emergent": 0.20,
                    "canopy": 0.45,
                    "understory": 0.30,
                    "shrub": 0.04,
                    "ground": 0.01
                },
                succession_stage="climax",
                disturbance_regime=["landslide", "earthquake", "flood"],
                conservation_priority=5,
                restoration_difficulty=4,
                typical_species_richness=200,
                carbon_storage_potential=300,
                water_regulation_capacity=5,
                soil_conservation_value=5
            )
        }
    
    @staticmethod
    def get_species_data() -> Dict[str, SpeciesTraits]:
        """Get comprehensive species trait data for Indian trees"""
        return {
            # Western Ghats Species
            "Cullenia exarillata": SpeciesTraits(
                scientific_name="Cullenia exarillata",
                common_name="Wild Durian",
                family="Malvaceae",
                native_states=["Kerala", "Karnataka", "Tamil Nadu"],
                layers=["emergent"],
                rainfall_min=2500, rainfall_max=6000,
                temp_min=18, temp_max=32,
                soil_ph_min=4.5, soil_ph_max=6.0,
                elevation_min=200, elevation_max=1200,
                growth_rate="slow",
                carbon_sequestration=350,
                wildlife_value=5,
                economic_value=2,
                medicinal_value=False,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=1,
                flood_tolerance=3,
                fire_resistance=1,
                iucn_status="VU",
                endemic_to=["Western Ghats"],
                cultural_significance="Sacred in tribal communities",
                flowering_months=[3, 4, 5],
                fruiting_months=[6, 7, 8],
                propagation_method=["seed"],
                nursery_availability=2,
                establishment_difficulty=4,
                maintenance_requirement=3
            ),
            
            "Holigarna arnottiana": SpeciesTraits(
                scientific_name="Holigarna arnottiana",
                common_name="Holigarna",
                family="Anacardiaceae",
                native_states=["Kerala", "Karnataka", "Tamil Nadu", "Maharashtra"],
                layers=["canopy"],
                rainfall_min=2000, rainfall_max=5000,
                temp_min=20, temp_max=35,
                soil_ph_min=5.0, soil_ph_max=6.5,
                elevation_min=100, elevation_max=1000,
                growth_rate="medium",
                carbon_sequestration=280,
                wildlife_value=4,
                economic_value=3,
                medicinal_value=True,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=2,
                flood_tolerance=4,
                fire_resistance=2,
                iucn_status="LC",
                endemic_to=["Western Ghats"],
                cultural_significance="Used in traditional medicine",
                flowering_months=[2, 3, 4],
                fruiting_months=[5, 6, 7],
                propagation_method=["seed", "cutting"],
                nursery_availability=3,
                establishment_difficulty=3,
                maintenance_requirement=2
            ),
            
            # Central Indian Species
            "Shorea robusta": SpeciesTraits(
                scientific_name="Shorea robusta",
                common_name="Sal",
                family="Dipterocarpaceae",
                native_states=["Madhya Pradesh", "Chhattisgarh", "Jharkhand", "West Bengal", "Assam"],
                layers=["emergent", "canopy"],
                rainfall_min=1000, rainfall_max=2500,
                temp_min=15, temp_max=40,
                soil_ph_min=5.5, soil_ph_max=7.0,
                elevation_min=200, elevation_max=1000,
                growth_rate="medium",
                carbon_sequestration=350,
                wildlife_value=5,
                economic_value=5,
                medicinal_value=True,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=3,
                flood_tolerance=2,
                fire_resistance=4,
                iucn_status="LC",
                endemic_to=[],
                cultural_significance="Sacred tree, state tree of Jharkhand",
                flowering_months=[3, 4, 5],
                fruiting_months=[6, 7],
                propagation_method=["seed"],
                nursery_availability=4,
                establishment_difficulty=2,
                maintenance_requirement=2
            ),
            
            "Tectona grandis": SpeciesTraits(
                scientific_name="Tectona grandis",
                common_name="Teak",
                family="Lamiaceae",
                native_states=["Madhya Pradesh", "Maharashtra", "Karnataka", "Kerala"],
                layers=["canopy"],
                rainfall_min=800, rainfall_max=2500,
                temp_min=20, temp_max=45,
                soil_ph_min=6.0, soil_ph_max=7.5,
                elevation_min=0, elevation_max=800,
                growth_rate="medium",
                carbon_sequestration=250,
                wildlife_value=3,
                economic_value=5,
                medicinal_value=False,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=4,
                flood_tolerance=2,
                fire_resistance=3,
                iucn_status="LC",
                endemic_to=[],
                cultural_significance="Premium timber species",
                flowering_months=[6, 7, 8],
                fruiting_months=[10, 11, 12],
                propagation_method=["seed"],
                nursery_availability=5,
                establishment_difficulty=2,
                maintenance_requirement=3
            ),
            
            "Madhuca longifolia": SpeciesTraits(
                scientific_name="Madhuca longifolia",
                common_name="Mahua",
                family="Sapotaceae",
                native_states=["Madhya Pradesh", "Chhattisgarh", "Jharkhand", "Maharashtra", "Odisha"],
                layers=["emergent", "canopy"],
                rainfall_min=800, rainfall_max=1800,
                temp_min=18, temp_max=42,
                soil_ph_min=6.0, soil_ph_max=8.0,
                elevation_min=100, elevation_max=800,
                growth_rate="slow",
                carbon_sequestration=300,
                wildlife_value=5,
                economic_value=4,
                medicinal_value=True,
                timber_value=False,
                fruit_value=True,
                nitrogen_fixing=False,
                drought_tolerance=4,
                flood_tolerance=2,
                fire_resistance=3,
                iucn_status="LC",
                endemic_to=[],
                cultural_significance="Sacred tree, flowers used for food and alcohol",
                flowering_months=[2, 3, 4],
                fruiting_months=[5, 6],
                propagation_method=["seed"],
                nursery_availability=3,
                establishment_difficulty=2,
                maintenance_requirement=1
            ),
            
            # Arid Zone Species
            "Prosopis cineraria": SpeciesTraits(
                scientific_name="Prosopis cineraria",
                common_name="Khejri",
                family="Fabaceae",
                native_states=["Rajasthan", "Gujarat", "Haryana", "Punjab"],
                layers=["canopy", "understory"],
                rainfall_min=150, rainfall_max=600,
                temp_min=5, temp_max=50,
                soil_ph_min=7.0, soil_ph_max=8.5,
                elevation_min=100, elevation_max=500,
                growth_rate="slow",
                carbon_sequestration=120,
                wildlife_value=4,
                economic_value=4,
                medicinal_value=True,
                timber_value=True,
                fruit_value=True,
                nitrogen_fixing=True,
                drought_tolerance=5,
                flood_tolerance=1,
                fire_resistance=3,
                iucn_status="LC",
                endemic_to=[],
                cultural_significance="State tree of Rajasthan, sacred to Bishnoi community",
                flowering_months=[3, 4, 5],
                fruiting_months=[6, 7, 8],
                propagation_method=["seed"],
                nursery_availability=4,
                establishment_difficulty=1,
                maintenance_requirement=1
            ),
            
            "Tecomella undulata": SpeciesTraits(
                scientific_name="Tecomella undulata",
                common_name="Rohida",
                family="Bignoniaceae",
                native_states=["Rajasthan", "Gujarat", "Haryana"],
                layers=["canopy"],
                rainfall_min=200, rainfall_max=500,
                temp_min=5, temp_max=48,
                soil_ph_min=7.5, soil_ph_max=8.5,
                elevation_min=100, elevation_max=400,
                growth_rate="slow",
                carbon_sequestration=100,
                wildlife_value=3,
                economic_value=4,
                medicinal_value=True,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=5,
                flood_tolerance=1,
                fire_resistance=4,
                iucn_status="VU",
                endemic_to=["Thar Desert"],
                cultural_significance="Desert teak, highly valued timber",
                flowering_months=[3, 4, 5],
                fruiting_months=[6, 7],
                propagation_method=["seed", "cutting"],
                nursery_availability=2,
                establishment_difficulty=3,
                maintenance_requirement=2
            ),
            
            # Himalayan Species
            "Quercus leucotrichophora": SpeciesTraits(
                scientific_name="Quercus leucotrichophora",
                common_name="Banj Oak",
                family="Fagaceae",
                native_states=["Himachal Pradesh", "Uttarakhand", "Jammu and Kashmir"],
                layers=["emergent", "canopy"],
                rainfall_min=1000, rainfall_max=2500,
                temp_min=5, temp_max=25,
                soil_ph_min=5.5, soil_ph_max=7.0,
                elevation_min=1200, elevation_max=2500,
                growth_rate="slow",
                carbon_sequestration=280,
                wildlife_value=5,
                economic_value=3,
                medicinal_value=False,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=2,
                flood_tolerance=3,
                fire_resistance=2,
                iucn_status="LC",
                endemic_to=["Himalayas"],
                cultural_significance="Keystone species of Himalayan oak forests",
                flowering_months=[3, 4],
                fruiting_months=[9, 10, 11],
                propagation_method=["seed"],
                nursery_availability=3,
                establishment_difficulty=3,
                maintenance_requirement=2
            ),
            
            "Pinus roxburghii": SpeciesTraits(
                scientific_name="Pinus roxburghii",
                common_name="Chir Pine",
                family="Pinaceae",
                native_states=["Himachal Pradesh", "Uttarakhand", "Jammu and Kashmir"],
                layers=["emergent", "canopy"],
                rainfall_min=800, rainfall_max=2000,
                temp_min=5, temp_max=35,
                soil_ph_min=5.0, soil_ph_max=7.5,
                elevation_min=500, elevation_max=2000,
                growth_rate="fast",
                carbon_sequestration=200,
                wildlife_value=2,
                economic_value=4,
                medicinal_value=False,
                timber_value=True,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=4,
                flood_tolerance=2,
                fire_resistance=5,
                iucn_status="LC",
                endemic_to=[],
                cultural_significance="Important for resin tapping",
                flowering_months=[3, 4],
                fruiting_months=[11, 12, 1],
                propagation_method=["seed"],
                nursery_availability=4,
                establishment_difficulty=2,
                maintenance_requirement=2
            ),
            
            # Eastern Himalayan Species
            "Magnolia campbellii": SpeciesTraits(
                scientific_name="Magnolia campbellii",
                common_name="Pink Tulip Tree",
                family="Magnoliaceae",
                native_states=["Sikkim", "Arunachal Pradesh", "West Bengal"],
                layers=["emergent"],
                rainfall_min=1500, rainfall_max=3500,
                temp_min=10, temp_max=25,
                soil_ph_min=5.0, soil_ph_max=6.5,
                elevation_min=1500, elevation_max=3000,
                growth_rate="slow",
                carbon_sequestration=320,
                wildlife_value=4,
                economic_value=2,
                medicinal_value=True,
                timber_value=False,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=1,
                flood_tolerance=3,
                fire_resistance=1,
                iucn_status="NT",
                endemic_to=["Eastern Himalayas"],
                cultural_significance="State tree of Sikkim, ornamental value",
                flowering_months=[2, 3, 4],
                fruiting_months=[8, 9, 10],
                propagation_method=["seed"],
                nursery_availability=2,
                establishment_difficulty=5,
                maintenance_requirement=4
            ),
            
            "Rhododendron arboreum": SpeciesTraits(
                scientific_name="Rhododendron arboreum",
                common_name="Tree Rhododendron",
                family="Ericaceae",
                native_states=["Himachal Pradesh", "Uttarakhand", "Sikkim", "Arunachal Pradesh"],
                layers=["canopy", "understory"],
                rainfall_min=1200, rainfall_max=3000,
                temp_min=5, temp_max=25,
                soil_ph_min=4.5, soil_ph_max=6.0,
                elevation_min=1200, elevation_max=3000,
                growth_rate="slow",
                carbon_sequestration=180,
                wildlife_value=5,
                economic_value=3,
                medicinal_value=True,
                timber_value=False,
                fruit_value=False,
                nitrogen_fixing=False,
                drought_tolerance=2,
                flood_tolerance=3,
                fire_resistance=2,
                iucn_status="LC",
                endemic_to=[],
                cultural_significance="State flower of Himachal Pradesh and Uttarakhand",
                flowering_months=[2, 3, 4, 5],
                fruiting_months=[8, 9, 10],
                propagation_method=["seed", "cutting"],
                nursery_availability=3,
                establishment_difficulty=4,
                maintenance_requirement=3
            )
        }
    
    @staticmethod
    def get_state_ecoregion_mapping() -> Dict[str, List[str]]:
        """Map Indian states to their ecoregions"""
        return {
            "Kerala": ["Western Ghats", "Malabar Coast"],
            "Karnataka": ["Western Ghats", "Deccan Plateau"],
            "Tamil Nadu": ["Western Ghats", "Eastern Ghats", "Deccan Plateau"],
            "Maharashtra": ["Western Ghats", "Deccan Plateau"],
            "Goa": ["Western Ghats", "Konkan Coast"],
            "Madhya Pradesh": ["Central Highlands", "Deccan Plateau"],
            "Chhattisgarh": ["Central Highlands", "Eastern Highlands"],
            "Jharkhand": ["Chota Nagpur Plateau", "Eastern Highlands"],
            "Odisha": ["Eastern Ghats", "Eastern Coastal Plains"],
            "West Bengal": ["Gangetic Plains", "Eastern Himalayas"],
            "Assam": ["Eastern Himalayas", "Brahmaputra Valley"],
            "Sikkim": ["Eastern Himalayas"],
            "Arunachal Pradesh": ["Eastern Himalayas"],
            "Himachal Pradesh": ["Western Himalayas"],
            "Uttarakhand": ["Western Himalayas"],
            "Jammu and Kashmir": ["Western Himalayas", "Trans Himalayas"],
            "Rajasthan": ["Thar Desert", "Aravalli Range"],
            "Gujarat": ["Thar Desert", "Western Coastal Plains"],
            "Haryana": ["Indo-Gangetic Plains", "Aravalli Range"],
            "Punjab": ["Indo-Gangetic Plains"]
        }
